var options = [
  `How do you want to feel at the end of today?`,
  `What are 3 things you're grateful for today?`,
  `What's one thing you'd like to do well today?`,
  `What's an important goal that you're working toward?`,
  `What working well in your life right now?`,
  `What are you looking forward to today?`,
  `What's something interesting you learned recently?`,
  `Where do you want to be a year from now?`,
  `What inspires you?`,
  `What's one area of your life you'd like to improve?`,
  `What can you do to set yourself up for success today?`,
  `What compliment can you give yourself right now?`,
  `What do you want to remember about this time in your life?`,
  `What most helps you feel relaxed?`,
  `What reminder do you want to give yourself today?`,
  `What have you learned about yourself in the last year?`,
  `What was the the highlight of your day yesterday?`,
  `What do you want to focus on today?`,
  `What are you most proud of?`,
  `What is your favorite memory of this year so far?`,
  `What aspects of your life bring you the most happiness right now?`,
  `What's something you'd like to get better at?`,
  `How would your life today amaze your childhood self?`,
  `What small step can you take to work toward reaching a goal today?`,
  `What are five things you appreciate about yourself?`,
  `What are you scared of right now?`,
  `What’s not working in your life right now?`,
  `Write someone a letter with whom you have an unresolved issue.`,
  `What would your ideal day look like?`,
  `When you were younger, what did you want to be when you grew up and why?`,
  `What’s something you wish others knew about you?`,
  `Who is someone you admire? What qualities do you love about them?`,
  `When you picture yourself 10 years from now, what do you want to have achieved and experienced?`,
  `What was the most peaceful moment during the day?`,
  `Describe something you learned today that you didn’t know before.`,
  `Would you change any of the decisions you made today?`,
  `Who do you wish you had talked to today? How do they improve your life?`,
  `Describe the moments of frustration you felt today. How would your day have changed if those moments were different?`,
  `Reflect on how your body feels. Where are you storing your stress? What put it there?`,
  `If you could relive any day of your life and change nothing, what day would you choose?`,
  `How would you like your life to be different in a year? How would you like it to be the same?`,
  `What was something you desperately wanted as a child? What do you desperately want now?`,
  `Rewrite a conversation you’ve had in the way you wish it had gone.`,
  `What was your best age so far?`,
  `Do you have a memory that should be happy, but instead makes you sad? What about the other way around?`,
  `When is a time in your life that you felt successful?`,
  `Write down 5 things that make you incredibly happy and describe why they make you feel this way.`,
  `What do you fear the most? Why? Is your fear rational?`,
  `What qualities about yourself do you love the most?`,
  `In the next year, what are 5 improvements you would like to make regarding your life?`,
  `Write about a difficult memory and the coping mechanisms you used at the time. Would you change the way you dealt? How?`,
  `Write about the last time you cried. What caused you to cry?`,
  `Write about the last time you laughed really hard. What was so funny?`,
  `Write a letter to the future YOU.`,
  `Write a letter to one of your parents`,
  `What has your anxiety taught you about yourself?`,
  `Write a letter to a person who has negatively impacted you.`,
  `Write a letter to a person who has positively impacted you.`,
  `Describe what love means to you. `,
  `Write a letter of forgiveness to yourself.`,
  `Write down 3 of your favorite smells. Describe, in detail, how each one makes you feel.`,
  `Have you ever felt isolated? Write about it.`,
  `Write about 5 songs that mean the most to you. Why do the lyrics speak to you? How do you relate to these songs? How do they make you feel when you hear them?`,
  `What risks do you want to take? What’s holding you back?`,
  `What element do you consider to be YOU? Write about why. (Earth, Air, Fire, Water).`,
  `Physically, how do you feel right now?`,
  `What speaks to you on an spiritual level?`,
  `What items/objects do you find the most comforting? Why do you think that is? What is comforting about them?`,
  `Write about something that is frustrating to you.`,
  `If you could be anywhere in the world at this very moment, where would you want to be and why?`,
  `What are 3 things that make you angry? Why?`,
  `When is the last time you did something for someone else? What did you do and how did it make you feel?`,
  `Write a letter to your teenage self telling him/her all the things you wish he/she knew.`,
  `What does self-care mean to you, and how can you incorporate this into your daily routine?`,
  `Describe a time you made a poor choice. What did you learn from the situation, and if you could have a do-over, what would you change about the situation?`,
  `Discuss 3 things you did RIGHT today.`,
  `Write a list of 10 things you are thankful for.`,
  `If you could have an hour with someone (living or dead) from your past, who would you choose and what would you ask him or her?`,
  `Write about an important person in your life who you are grateful for. What do you admire about this person, why have they had such an impact on your life, and what would you like to tell them?`,
  `How do you want to feel tomorrow, and what 3 things can you do today to ensure you feel that way?`,
  `What’s the most embarrassing thing that ever happened to you?`,
  `What are your best character traits?`,
  `What is your 5-year plan? Map out all of the things you need to do to reach your goals.`,
  `Describe your favorite time of year. What do you love about it, who do you spend it with, and what activities do you enjoy during that time?`,
  `What makes you feel fulfilled?`,
  `Make a list of things that are holding you back from your wants, needs, goals, and desires. Be brutally honest with yourself, and brainstorm ways to overcome these obstacles.`
];

function getRandomOption() {
  return options[Math.floor(Math.random() * options.length)];
}

var optionText = document.getElementById('optionText');
var setNewOption = document.getElementById('setNewOption');

optionText.innerHTML = getRandomOption();

setNewOption.addEventListener('click', function(e) {
  e.preventDefault();
  
  optionText.innerHTML = getRandomOption();
})